/**
 * Contenido de las hojas «INDEPENDIENTE» y «EMPLEADO y PENSIONADO»
 * de `docs/PLANTILLA ANALISIS Y SCOREn Modificado.xlsx` (valores y textos de referencia).
 */

export type ScoreMatrixLine =
  | { k: 's'; label: string; peso: string; max: string }
  | { k: 'r'; v: string; p: string; d: string; h: string; pt: string }

/** Hoja INDEPENDIENTE — matriz de variables y puntajes (total formulario 1000). */
export const INDEPENDIENTE_MATRIX: ScoreMatrixLine[] = [
  { k: 's', label: 'CUALITATIVAS', peso: '0.3', max: '300' },
  { k: 'r', v: 'Antigüedad como asociado', p: '0.2', d: '0 meses', h: '24', pt: '10' },
  { k: 'r', v: '', p: '', d: '25', h: '60', pt: '35' },
  { k: 'r', v: '', p: '', d: '61', h: '120', pt: '45' },
  { k: 'r', v: '', p: '', d: '121', h: '540', pt: '60' },
  { k: 'r', v: 'Actividad que desarrolla', p: '0.3', d: 'Independientes (abogados, contadores, etc.)', h: '', pt: '40' },
  { k: 'r', v: '', p: '', d: 'Comercio formal', h: '', pt: '90' },
  { k: 'r', v: '', p: '', d: 'Comercio informal', h: '', pt: '35' },
  { k: 'r', v: '', p: '', d: 'Transportadores', h: '', pt: '50' },
  { k: 'r', v: '', p: '', d: 'Agropecuario', h: '', pt: '80' },
  { k: 'r', v: 'Antigüedad en la actividad', p: '0.35', d: '6 meses', h: '24', pt: '30' },
  { k: 'r', v: '', p: '', d: '25', h: '60', pt: '60' },
  { k: 'r', v: '', p: '', d: '61', h: '120', pt: '80' },
  { k: 'r', v: '', p: '', d: '121', h: '540', pt: '105' },
  { k: 'r', v: 'Edad', p: '0.1', d: '18 años', h: '25', pt: '10' },
  { k: 'r', v: '', p: '', d: '26', h: '50', pt: '30' },
  { k: 'r', v: '', p: '', d: '51', h: '84', pt: '20' },
  { k: 'r', v: 'Estado civil', p: '0.05', d: 'Soltero', h: '', pt: '7' },
  { k: 'r', v: '', p: '', d: 'Casado', h: '', pt: '15' },
  { k: 'r', v: '', p: '', d: 'Unión libre', h: '', pt: '9' },
  { k: 'r', v: '', p: '', d: 'Viudo', h: '', pt: '8' },
  { k: 'r', v: '', p: '', d: 'Separado', h: '', pt: '8' },
  { k: 's', label: 'CUANTITATIVAS', peso: '0.7', max: '700' },
  { k: 'r', v: 'Calificación en centrales de riesgo (SCORE)', p: '0.15', d: '0 - 450', h: '', pt: '30' },
  { k: 'r', v: '', p: '', d: '451 - 600', h: '', pt: '70' },
  { k: 'r', v: '', p: '', d: '601 en adelante', h: '', pt: '105' },
  { k: 'r', v: 'Hábito de pago en centrales de riesgo', p: '0.2', d: 'Bueno', h: '', pt: '140' },
  { k: 'r', v: '', p: '', d: 'Regular', h: '', pt: '70' },
  { k: 'r', v: '', p: '', d: 'Malo', h: '', pt: '0' },
  { k: 'r', v: '', p: '', d: 'No tiene experiencia', h: '', pt: '10' },
  { k: 'r', v: 'Nivel de endeudamiento (total pasivo / bien raíz) = %', p: '0.15', d: '0', h: '0.4', pt: '105' },
  { k: 'r', v: '', p: '', d: '0.41', h: '0.6', pt: '75' },
  { k: 'r', v: '', p: '', d: '>60%', h: '', pt: '0' },
  { k: 'r', v: 'Reestructuraciones (vigentes)', p: '0.05', d: 'Sin reestructuraciones', h: '', pt: '35' },
  { k: 'r', v: '', p: '', d: '1 reestructuración', h: '', pt: '20' },
  { k: 'r', v: '', p: '', d: '2 o más reestructuraciones', h: '', pt: '0' },
  { k: 'r', v: 'Comportamiento en Coopservivelez', p: '0.15', d: 'Bueno', h: '', pt: '105' },
  { k: 'r', v: '', p: '', d: 'Regular', h: '', pt: '70' },
  { k: 'r', v: '', p: '', d: 'Malo', h: '', pt: '0' },
  { k: 'r', v: '', p: '', d: 'No tiene experiencia', h: '', pt: '10' },
  { k: 'r', v: 'Garantía', p: '0.2', d: 'Hipotecario', h: '', pt: '140' },
  { k: 'r', v: '', p: '', d: 'Deudor y codeudor con bien raíz', h: '', pt: '120' },
  { k: 'r', v: '', p: '', d: 'Codeudor con bien raíz', h: '', pt: '100' },
  { k: 'r', v: '', p: '', d: 'Codeudor con bien raíz y FNG', h: '', pt: '105' },
  { k: 'r', v: '', p: '', d: 'FNG', h: '', pt: '80' },
  { k: 'r', v: '', p: '', d: 'Firma personal', h: '', pt: '40' },
  { k: 'r', v: '', p: '', d: 'CDAT', h: '', pt: '140' },
  { k: 'r', v: '', p: '', d: 'APORTES', h: '', pt: '140' },
  { k: 'r', v: 'Solvencia del deudor (activo / pasivo)', p: '0.1', d: '0', h: '0.35', pt: '70' },
  { k: 'r', v: '', p: '', d: '0.36', h: '0.7', pt: '35' },
  { k: 'r', v: '', p: '', d: '> 70%', h: '', pt: '0' },
]

/** Hoja EMPLEADO y PENSIONADO. */
export const EMPLEADO_PENSIONADO_MATRIX: ScoreMatrixLine[] = [
  { k: 's', label: 'CUALITATIVAS', peso: '0.3', max: '300' },
  { k: 'r', v: 'Antigüedad como asociado', p: '0.25', d: '0 meses', h: '24', pt: '15' },
  { k: 'r', v: '', p: '', d: '25', h: '60', pt: '35' },
  { k: 'r', v: '', p: '', d: '61', h: '120', pt: '50' },
  { k: 'r', v: '', p: '', d: '121', h: '540', pt: '75' },
  { k: 'r', v: 'Edad', p: '0.1', d: '18 años', h: '25', pt: '10' },
  { k: 'r', v: '', p: '', d: '26', h: '50', pt: '30' },
  { k: 'r', v: '', p: '', d: '51', h: '84', pt: '20' },
  { k: 'r', v: 'Estado civil', p: '0.05', d: 'Soltero', h: '', pt: '7' },
  { k: 'r', v: '', p: '', d: 'Casado', h: '', pt: '15' },
  { k: 'r', v: '', p: '', d: 'Unión libre', h: '', pt: '9' },
  { k: 'r', v: '', p: '', d: 'Viudo', h: '', pt: '8' },
  { k: 'r', v: '', p: '', d: 'Separado', h: '', pt: '8' },
  { k: 'r', v: 'Tipo de contrato', p: '0.3', d: 'Indefinido o pensión', h: '', pt: '90' },
  { k: 'r', v: '', p: '', d: 'Fijo', h: '', pt: '50' },
  { k: 'r', v: '', p: '', d: 'Prestación de servicios', h: '', pt: '30' },
  { k: 'r', v: '', p: '', d: 'Informal', h: '', pt: '5' },
  { k: 'r', v: 'Antigüedad laboral', p: '0.3', d: '0 meses', h: '24', pt: '25' },
  { k: 'r', v: '', p: '', d: '25', h: '60', pt: '50' },
  { k: 'r', v: '', p: '', d: '61', h: '120', pt: '70' },
  { k: 'r', v: '', p: '', d: '121', h: '540', pt: '90' },
  { k: 's', label: 'CUANTITATIVAS', peso: '0.7', max: '700' },
  { k: 'r', v: 'Calificación en centrales de riesgo (SCORE)', p: '0.15', d: '0 - 450', h: '', pt: '30' },
  { k: 'r', v: '', p: '', d: '451 - 600', h: '', pt: '70' },
  { k: 'r', v: '', p: '', d: '601 en adelante', h: '', pt: '105' },
  { k: 'r', v: 'Hábito de pago en centrales de riesgo', p: '0.2', d: 'Bueno', h: '', pt: '140' },
  { k: 'r', v: '', p: '', d: 'Regular', h: '', pt: '70' },
  { k: 'r', v: '', p: '', d: 'Malo', h: '', pt: '0' },
  { k: 'r', v: '', p: '', d: 'No tiene experiencia', h: '', pt: '10' },
  { k: 'r', v: 'Nivel de endeudamiento (total pasivo / bien raíz) = %', p: '0.15', d: '0', h: '0.4', pt: '105' },
  { k: 'r', v: '', p: '', d: '0.41', h: '0.6', pt: '75' },
  { k: 'r', v: '', p: '', d: '>60%', h: '', pt: '0' },
  { k: 'r', v: 'Reestructuraciones (vigentes)', p: '0.05', d: 'Sin reestructuraciones', h: '', pt: '35' },
  { k: 'r', v: '', p: '', d: '1 reestructuración', h: '', pt: '20' },
  { k: 'r', v: '', p: '', d: '2 o más reestructuraciones', h: '', pt: '0' },
  { k: 'r', v: 'Comportamiento en Coopservivelez', p: '0.15', d: 'Bueno', h: '', pt: '105' },
  { k: 'r', v: '', p: '', d: 'Regular', h: '', pt: '70' },
  { k: 'r', v: '', p: '', d: 'Malo', h: '', pt: '0' },
  { k: 'r', v: '', p: '', d: 'No tiene experiencia', h: '', pt: '10' },
  { k: 'r', v: 'Garantía', p: '0.2', d: 'Libranza (Coopservivelez)', h: '', pt: '80' },
  { k: 'r', v: '', p: '', d: 'Hipotecario', h: '', pt: '140' },
  { k: 'r', v: '', p: '', d: 'Deudor y codeudor con bien raíz', h: '', pt: '120' },
  { k: 'r', v: '', p: '', d: 'Codeudor con bien raíz', h: '', pt: '100' },
  { k: 'r', v: '', p: '', d: 'Codeudor con bien raíz y FNG', h: '', pt: '105' },
  { k: 'r', v: '', p: '', d: 'FNG', h: '', pt: '80' },
  { k: 'r', v: '', p: '', d: 'Firma personal', h: '', pt: '40' },
  { k: 'r', v: '', p: '', d: 'CDAT', h: '', pt: '140' },
  { k: 'r', v: '', p: '', d: 'APORTES', h: '', pt: '140' },
  { k: 'r', v: 'Solvencia del deudor (activo / pasivo)', p: '0.1', d: '0', h: '0.35', pt: '70' },
  { k: 'r', v: '', p: '', d: '0.36', h: '0.7', pt: '35' },
  { k: 'r', v: '', p: '', d: '> 70%', h: '', pt: '0' },
]
